### PR TITLE
FE fixed Issue#51

### LINKED ISSUE #51: [FE][Bug] Page refresh on Home/About leads to 404 error
Refreshing the live Webpage on any route except the default one, leads to a nginx 404 Not Found Error.

### PR DESCRIPTION
**Pull request by WilhelmStu**
Fixed #51 and added UI tests to detect similar issues in the future

### CODE REVIEW

File: selenium/src/test/java/at/stulpinger/ase/UITest.java [hunk 1]
```diff
@@ -111,4 +116,32 @@ public void navigate_toAboutAndBack() {
     navigateToHomePage.click();
   }
 
+  @Test
+  public void reload_about() {
+    openApplicationWithPath("about");
```
Comment (fragjulian) [inline selenium/src/test/java/at/stulpinger/ase/UITest.java:121]: you could create constants for these paths (or maybe an enum)

**Review by fragjulian — APPROVED** [review]

**Review by fragjulian — APPROVED** [review]
